### PR TITLE
Dockerfile and Docker hub integration

### PR DESCRIPTION
**Pull request by otrosien**
Includes maven wrapper to make it easier to build inside docker

Points to my dockerhub at the moment to show how the result would look like, of course it would be better if you @olivergierke would build an official docker image.

See https://docs.docker.com/docker-hub/github/
Closes issue #30

### CODE REVIEW

**Comment by olivergierke** [comment]
Where's the need to run this in Docker in the first place? The app just runs fine as is when packaged. I am not inclined to add any more infrastructure to it as its main purpose is to show how to implement a hypermedia driven API, not how to run a Spring Boot app in Docker.

**Comment by otrosien** [comment]
The maven build is called from docker, because that is the only way if you want to have it built on docker hub directly, instead of building and pushing it from your own CI infrastructure.

It would be a convenience for people that only want to showcase the Restbucks example without having the source code, java, maven, etc. installed locally.

**Comment by otrosien** [comment]
It may be questionable to dockerize spring-restbucks, because there are basically no releases, but only ongoing development in master - and running it from the source code is a one-liner anyway. In other words, I won't be offended if you choose not to merge this ;-)

**Comment by olivergierke** [comment]
So in the light of the project being an example of how to *implement* a hypermedia based system, I'll go ahead and close this one without merging. Thanks, nonetheless!

**Pull request closed without merging**
