### PR TITLE
happy new year 2016

### PR DESCRIPTION
**Pull request by otrosien**
http://www.commitstrip.com/en/2015/12/31/happy-new-year-2016/

### CODE REVIEW

**Comment by otrosien** [comment]
I copied the changes from pull #41 here as well.

**Comment by olivergierke** [comment]
I am afraid to say this, but I have the same problem with this PR that I have with the former one: it's a bunch of unrelated changes, topped by a quite meaningless description.

So if you want to raise the chance to get anything merged, please make sure you follow these items:

1. Create a PR with a meaningful, concise,  description of an atomic change, e.g. "Removed version numbers from readme."
2. Make sure the PR contains a commit message that makes clear *why* the change is needed. Slapping some annotation on a class doesn't cut it.
3. Don't mix up three different changes (tweak of the `.gitignore`, some Jackson stuff, some new converter (why is this even needed? See 2.)).

I'm not gonna merge arbitrary unrelated changes as I'm the one who has to maintain this going forward, and I'd like to be able to make sense of stuff whenever I come back to the codw, which — with the current state of affairs — is impossible.

**Comment by otrosien** [comment]
I see your point. Then, let's try to break it down to separate changesets with proper description. I'll be right back :)

**Comment by olivergierke** [comment]
Awesome, thanks! 🙃

**Pull request closed without merging**
